# Generated by Django 5.0 on 2023-12-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('EmailId', models.CharField(max_length=40)),
                ('Guest', models.CharField(max_length=10)),
                ('CheckInDate', models.DateField(max_length=10)),
                ('Destination', models.CharField(max_length=20)),
            ],
        ),
    ]
