# Generated by Django 5.0 on 2024-01-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailId', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
